name: Deploy to github pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    steps:
      - name: Publish to Github Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/musatcristian/books-tracker-FE.git
          npm run deploy -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}